#!/usr/bin/env bash

set -e

# Updating pip and setuptools because some older versions don't recognize the
# project setup correctly
if [[ $1 != '--no-pip' ]]; then
    pip install --upgrade pip
fi
pip install --upgrade setuptools

# Installing PFERD itself
pip install --editable .

# Installing tools and type hints
pip install --upgrade mypy flake8 autopep8 isort pyinstaller
mypy PFERD --install-types --non-interactive
