name: build-and-release

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - name: Set up project
        run: uv sync

      - name: Build
        run: |
          ./scripts/build-python-dist

      - name: Upload binary
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: python-dist
          path: dist/

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15-intel, macos-latest]
        python: ["3.11"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          python-version: ${{ matrix.python }}

      - name: Set up project
        run: uv sync

      - name: Run checks
        run: |
          ./scripts/check
          ./scripts/format

      - name: Assert no changes
        run: git diff --exit-code

      - name: Build
        run: |
          ./scripts/build
          ./dist/pferd${{ matrix.os == 'windows-latest' && '.exe' || '' }} --version

      - name: Rename binary
        # Glob in source location because on windows pyinstaller creates a file
        # named "pferd.exe"
        run: mv dist/pferd* dist/pferd-${{ matrix.os }}

      - name: Upload binary
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: pferd-${{ matrix.os }}
          path: dist/pferd-${{ matrix.os }}

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      id-token: write
    needs:
      - build
      - build-python
    environment: pypi
    steps:
      - name: Download binaries
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: pferd-*
          merge-multiple: true

      - name: Rename binaries
        run: |
          mv pferd-ubuntu-latest pferd-linux
          mv pferd-windows-latest pferd-windows.exe
          mv pferd-macos-15-intel pferd-mac-x86_64
          mv pferd-macos-latest pferd-mac

      - name: Download Python dist
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: python-dist
          path: dist

      - name: Publish package on PyPi
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0

      - name: Create release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            pferd-linux
            pferd-windows.exe
            pferd-mac
            pferd-mac-x86_64
